name: Bump Patch Version

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

jobs:
  run:
    name: Bump Patch Version
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'bump-patch-version')
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.10.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.x
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true

      - name: Bump version
        run: poetry version patch

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: Bump version number
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: 'pyproject.toml'
